import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { parseManifest } from './manifest.mjs';
import { scrubPrivateLinks } from './hygiene.mjs';
import { writeChannelReleaseNotes } from './release-notes.mjs';
import { RAW_DIR, DERIVED_DIR, generateReference } from './generate.mjs';

// Beta ingestion. A bundle directory laid out per the docs-bundle contract:
//   manifest.json, reference/cli/**, release-notes.md
// is applied by WHOLESALE replacement of reference-raw/ (never merge), so
// files deleted upstream disappear here and re-runs of the same tag are no-ops.
// The bundle's raw pages become the committed source in reference-raw/; the
// derived help dump under reference-derived/ is produced from that source +
// prose overlays by generateReference (so CI can prove it correct). Published
// CLI docs under content/docs/<channel>/reference/cli/ are human-authored.

async function readJson(path) {
  return JSON.parse(await readFile(path, 'utf8'));
}

async function writeJson(path, obj) {
  await writeFile(path, JSON.stringify(obj, null, 2) + '\n');
}

// meta.json / meta.vi.json are human-owned nav config (localized sidebar labels
// + ordering). They live in the generated dir but are NOT machine-generated, so
// sync must preserve them and the guard must allow humans to edit them.
export const isNavMeta = (name) => /^meta(\.[\w-]+)?\.json$/.test(name);

/**
 * Apply a beta docs bundle to the repo.
 * @param {{repoRoot: string, bundleDir: string}} args
 * @returns {Promise<{tag:string, sha:string, version:string, channel:'beta', referenceFiles:number}>}
 */
export async function syncBetaRelease({ repoRoot, bundleDir }) {
  const manifest = parseManifest(
    await readFile(join(bundleDir, 'manifest.json'), 'utf8'),
    { expectedChannel: 'beta' },
  );
  const { tag, sha, version, generatedAt } = manifest;

  const betaDir = join(repoRoot, 'content', 'docs', 'beta');
  const derivedDir = join(repoRoot, DERIVED_DIR);
  const bundleCli = join(bundleDir, 'reference', 'cli');

  // 1. Refresh the raw source from the bundle, then derive the help dump.
  // reference-raw/ holds the hygiene-scrubbed `ak --help` projection (wholesale
  // replaced, so upstream deletions vanish); a bundle-provided meta is never
  // stored there. generateReference then produces reference-derived/ from
  // reference-raw + prose overlays.
  const rawDir = join(repoRoot, RAW_DIR);
  await mkdir(rawDir, { recursive: true });
  for (const e of await readdir(rawDir, { withFileTypes: true })) {
    if (e.isFile() && /\.mdx?$/.test(e.name)) await rm(join(rawDir, e.name));
  }
  for (const e of await readdir(bundleCli, { withFileTypes: true })) {
    if (!e.isFile() || isNavMeta(e.name) || !/\.mdx?$/.test(e.name)) continue;
    await writeFile(join(rawDir, e.name), scrubPrivateLinks(await readFile(join(bundleCli, e.name), 'utf8')));
  }
  await mkdir(derivedDir, { recursive: true });
  const referenceFiles = await generateReference({ repoRoot });

  // 2. Rewrite the machine-owned marker with this tag's provenance.
  await writeJson(join(derivedDir, '.generated'), {
    generator: 'ak-cli-reference',
    source: 'ak-cli',
    tag,
    sha,
    generatedAt,
    note: 'Machine-owned directory generated by the release-sync pipeline. Do not hand-edit.',
  });

  // 3. Release notes → MDX with channel/tag frontmatter + hygiene scrub.
  const notes = await readFile(join(bundleDir, 'release-notes.md'), 'utf8');
  await writeChannelReleaseNotes({ channelDir: betaDir, channel: 'beta', tag, body: notes });

  // 4. channels.json.beta — deterministic (syncedAt = manifest generatedAt).
  const channelsPath = join(repoRoot, 'channels.json');
  const channels = await readJson(channelsPath);
  channels.beta = { version, tag, sha, syncedAt: generatedAt };
  await writeJson(channelsPath, channels);

  return { tag, sha, version, channel: 'beta', referenceFiles };
}
